version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr_employee_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/hr_system
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    networks:
      - hrnet